import type { AdoptionDecision, BenchmarkEntry } from '../types/githubBenchmark';

export const BENCHMARK_VERIFIED_AT = '2026-03-12';

export const benchmarkEntries: readonly BenchmarkEntry[] = [
    {
        repo: 'wataru-maeda/react-native-boilerplate',
        license: 'MIT',
        maintenance_status: 'active',
        stack_match: 'strong',
        best_fit_area: ['foundation', 'data'],
        adoptability: 'high',
        risk: 'low',
        current_app_mapping: ['auth-session', 'notifications', 'offline-cache'],
        recommended_action: {
            foundation: 'adopt pattern',
            data: 'borrow structure',
            'clinical-workflow': 'reject',
        },
        shortlist: true,
        rank: 1,
        last_pushed_at: '2026-02-23T03:25:34Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        notes: [
            'Strong Expo SDK 54, React 19, Expo Router, and web deployment alignment.',
            'Best source for app-shell hardening, CI workflow shape, and environment handling.',
        ],
        sources: [
            'https://github.com/wataru-maeda/react-native-boilerplate',
            'https://api.github.com/repos/wataru-maeda/react-native-boilerplate',
        ],
    },
    {
        repo: 'roninoss/create-expo-stack',
        license: 'MIT',
        maintenance_status: 'active',
        stack_match: 'strong',
        best_fit_area: ['foundation', 'data'],
        adoptability: 'high',
        risk: 'low',
        current_app_mapping: ['auth-session', 'offline-cache'],
        recommended_action: {
            foundation: 'adopt pattern',
            data: 'borrow structure',
            'clinical-workflow': 'reject',
        },
        shortlist: true,
        rank: 2,
        last_pushed_at: '2026-02-28T00:23:52Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        notes: [
            'Useful as a generator-level reference for Expo Router, Firebase, and environment choices.',
            'Less reusable as runtime code, but very strong for setup conventions and dependency hygiene.',
        ],
        sources: [
            'https://github.com/roninoss/create-expo-stack',
            'https://api.github.com/repos/roninoss/create-expo-stack',
        ],
    },
    {
        repo: 'margelo/react-native-nitro-sqlite',
        license: 'MIT',
        maintenance_status: 'active',
        stack_match: 'medium',
        best_fit_area: ['data'],
        adoptability: 'high',
        risk: 'medium',
        current_app_mapping: ['checkins', 'history', 'resources', 'offline-cache'],
        recommended_action: {
            foundation: 'reject',
            data: 'adopt pattern',
            'clinical-workflow': 'reject',
        },
        shortlist: true,
        rank: 3,
        last_pushed_at: '2026-03-10T10:45:19Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        notes: [
            'Best match for a heavier local read cache or offline repository layer.',
            'Needs integration care because the app currently leans on AsyncStorage and Firestore.',
        ],
        sources: [
            'https://github.com/margelo/react-native-nitro-sqlite',
            'https://api.github.com/repos/margelo/react-native-nitro-sqlite',
        ],
    },
    {
        repo: 'instamobile/react-native-firebase',
        license: 'MIT',
        maintenance_status: 'moderate',
        stack_match: 'medium',
        best_fit_area: ['foundation', 'data'],
        adoptability: 'medium',
        risk: 'medium',
        current_app_mapping: ['notifications', 'auth-session', 'resources'],
        recommended_action: {
            foundation: 'borrow structure',
            data: 'borrow structure',
            'clinical-workflow': 'reject',
        },
        shortlist: true,
        rank: 4,
        last_pushed_at: '2024-11-06T19:39:24Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        notes: [
            'Good reference for Firebase auth, persisted sessions, Firestore reads/writes, and push setup.',
            'Navigation stack is older than the current Expo Router app, so reuse should stay pattern-level.',
        ],
        sources: [
            'https://github.com/instamobile/react-native-firebase',
            'https://api.github.com/repos/instamobile/react-native-firebase',
        ],
    },
    {
        repo: 'hppanpaliya/MindfulMe',
        license: 'MIT',
        maintenance_status: 'stale',
        stack_match: 'low',
        best_fit_area: ['clinical-workflow', 'reference-only'],
        adoptability: 'low',
        risk: 'medium',
        current_app_mapping: ['checkins', 'history', 'resources', 'templates'],
        recommended_action: {
            foundation: 'reject',
            data: 'reject',
            'clinical-workflow': 'borrow UX only',
        },
        shortlist: true,
        rank: 5,
        last_pushed_at: '2024-04-26T17:33:14Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        notes: [
            'Useful for feature packaging and dashboard grouping around mental well-being tools.',
            'Web-first implementation and stale maintenance make it a UX reference, not an architectural base.',
        ],
        sources: [
            'https://github.com/hppanpaliya/MindfulMe',
            'https://api.github.com/repos/hppanpaliya/MindfulMe',
        ],
    },
    {
        repo: 'leokhoa/nomie',
        license: 'NONE',
        maintenance_status: 'stale',
        stack_match: 'low',
        best_fit_area: ['clinical-workflow', 'reference-only'],
        adoptability: 'reference-only',
        risk: 'high',
        current_app_mapping: ['checkins', 'history'],
        recommended_action: {
            foundation: 'reject',
            data: 'reject',
            'clinical-workflow': 'reject',
        },
        shortlist: false,
        rank: null,
        last_pushed_at: '2019-09-24T20:53:11Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        rejection_reason: 'No clear MIT/Apache license in the repository metadata and the project is very stale.',
        notes: [
            'The product direction is interesting for journaling and mood tracking.',
            'Keep it out of the reusable benchmark because licensing and maintenance are both weak.',
        ],
        sources: [
            'https://github.com/leokhoa/nomie',
            'https://api.github.com/repos/leokhoa/nomie',
        ],
    },
    {
        repo: 'nandorojo/expo-firestore-offline-persistence',
        license: 'MIT',
        maintenance_status: 'deprecated',
        stack_match: 'medium',
        best_fit_area: ['reference-only', 'data'],
        adoptability: 'reference-only',
        risk: 'high',
        current_app_mapping: ['offline-cache', 'checkins', 'history'],
        recommended_action: {
            foundation: 'reject',
            data: 'reject',
            'clinical-workflow': 'reject',
        },
        shortlist: false,
        rank: null,
        last_pushed_at: '2023-01-06T10:19:34Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        rejection_reason: 'Repository README explicitly says it is no longer maintained.',
        notes: [
            'Still useful for understanding earlier Expo + Firestore offline workarounds.',
            'Do not introduce it as a dependency or copy its approach into the current stack.',
        ],
        sources: [
            'https://github.com/nandorojo/expo-firestore-offline-persistence',
            'https://api.github.com/repos/nandorojo/expo-firestore-offline-persistence',
        ],
    },
    {
        repo: 'barthap/with-rn-firebase',
        license: 'NONE',
        maintenance_status: 'deprecated',
        stack_match: 'medium',
        best_fit_area: ['reference-only', 'foundation'],
        adoptability: 'reference-only',
        risk: 'high',
        current_app_mapping: ['auth-session', 'notifications'],
        recommended_action: {
            foundation: 'reject',
            data: 'reject',
            'clinical-workflow': 'reject',
        },
        shortlist: false,
        rank: null,
        last_pushed_at: '2021-07-29T08:44:45Z',
        verified_at: BENCHMARK_VERIFIED_AT,
        rejection_reason: 'README marks the plugin as deprecated and the repository metadata does not expose a clear MIT/Apache license.',
        notes: [
            'Historical context for older Expo config-plugin flows only.',
            'Do not use for current Expo SDK 54 or React Native Firebase planning.',
        ],
        sources: [
            'https://github.com/barthap/with-rn-firebase',
            'https://api.github.com/repos/barthap/with-rn-firebase',
        ],
    },
] as const;

export const rankedShortlist = benchmarkEntries
    .filter((entry) => entry.shortlist)
    .sort((left, right) => (left.rank ?? Number.MAX_SAFE_INTEGER) - (right.rank ?? Number.MAX_SAFE_INTEGER));

export const excludedRepos = benchmarkEntries.filter((entry) => !entry.shortlist);

export const adoptionDecisions: readonly AdoptionDecision[] = [
    {
        id: 'offline-read-cache-spike',
        title: 'Offline/read cache spike for checkins, history, and resources',
        order: 1,
        track: 'data',
        outcome: 'spike',
        repos: ['margelo/react-native-nitro-sqlite', 'wataru-maeda/react-native-boilerplate'],
        affected_modules: ['modules/checkins', 'modules/history', 'modules/resources', 'modules/shared'],
        expected_effort: '2 weeks',
        acceptance_criteria: [
            'Cold-start reads work for checkins and history without a network connection.',
            'Resources list uses the same repository boundary and cache invalidation strategy as checkins/history.',
            'The spike does not regress the current AsyncStorage-backed cache behavior before cutover.',
        ],
    },
    {
        id: 'notification-inbox-consistency-spike',
        title: 'Notification delivery and inbox consistency across push, email, and web',
        order: 2,
        track: 'clinical-workflow',
        outcome: 'spike',
        repos: ['instamobile/react-native-firebase', 'hppanpaliya/MindfulMe'],
        affected_modules: ['functions', 'modules/checkins', 'modules/resources', 'app/(app)', 'services'],
        expected_effort: '2 weeks',
        acceptance_criteria: [
            'A single notification event resolves to the correct in-app inbox entry and fallback channel.',
            'Notification state is visible from both the therapist workflow and the client-facing app shell.',
            'Email and push templates keep the deployed web app URL as the canonical deep-link target.',
        ],
    },
    {
        id: 'app-shell-hardening-spike',
        title: 'App-shell hardening for config, testability, and Expo/Firebase ergonomics',
        order: 3,
        track: 'foundation',
        outcome: 'spike',
        repos: ['wataru-maeda/react-native-boilerplate', 'roninoss/create-expo-stack', 'instamobile/react-native-firebase'],
        affected_modules: ['app', 'src', 'functions', 'tests', 'utils'],
        expected_effort: '2 weeks',
        acceptance_criteria: [
            'Environment handling is explicit for local, preview, and production deploy flows.',
            'The web build and Firebase deploy path stay green after the refactor.',
            'At least one shared test harness pattern is documented and reused for future module tests.',
        ],
    },
] as const;
